# -*- coding: utf-8 -*-
"""desafio2_algoritmos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13flvIWj9oO0yhMIeubEQQi3QtjGD8nHc

1. A imobiliária Imóbilis vende apenas terrenos retangulares. Faça um script em Python para ler as dimensões de um terreno e depois exibir a área do terreno.
"""

base = float(input('Digite o valor da base: '))
altura = float(input('Digite o valor da altura: '))
area = base * altura
print('A área total do terreno retangular é:', area)

"""2. Faça um script em Python para calcular quantas ferraduras são necessárias para equipar todos os cavalos comprados para um haras."""

cavalos = int(input('Digite a quantidade de cavalos do haras: '))
qtd_ferraduras = cavalos * 4
print('A quantidade ideal de ferraduras para todos os cavalos são', qtd_ferraduras)

"""3. A padaria Hotpão vende uma certa quantidade de pães franceses e uma quantidade de broas a cada dia. Cada pãozinho custa 0.12 e a broa custa 1.50. Ao final do dia, o dono quer saber quanto arrecadou com a venda dos pães e broas (juntos), e quanto deve guardar numa conta de poupança (10% do total arrecadado). Você foi contratado para fazer os cálculos para o dono. Com base nestes fatos, faça um script em Python para ler as quantidades de pães e de broas, e depois calcular os dados solicitados."""

paes = float(input('digite a quantidade de paes: '))
broas = float(input('digite a quantidade de broas: '))

paes_total = paes * 0.12
broas_total = broas * 1.5
total = paes_total + broas_total
poupanca = total * 0.1

print('valor total vendido:', total, 'valor para guardar:', poupanca)

"""4. Escreva um script em Python para ler o nome e a idade de uma pessoa, e exibir quantos dias de vida ela possui. Considere sempre anos completos, e que um ano possui 365 dias. Ex: uma pessoa
com 19 anos possui 6935 dias de vida; veja um exemplo de saída: MARIA, VOCÊ JÁ VIVEU 6935 DIAS
"""

nome = input('Digite o seu nome: ')
idade = int(input('digite a sua idade em anos: '))

dias_vividos = idade * 365

print(nome + ',', 'você já viveu', dias_vividos, 'dias')

"""5. Um motorista deseja colocar no seu tanque X reais de gasolina. Escreva um script em Python para ler o preço do litro da gasolina e o valor do pagamento, e exibir quantos litros ele conseguiu colocar no tanque."""

gasolina = float(input('digite o preco do litro da gasolina: '))
dinheiro = float(input('valor que deseja comprar de gasolina: '))

litros = dinheiro / gasolina

print('voce abasteceu', litros, 'de gasolina.')

"""6. O restaurante a quilo Bem-Bão cobra R$12,00 por cada quilo de refeição. Escreva um script em Python que leia o peso do prato montado pelo cliente (em quilos) e imprima o valor a pagar. Assuma que a balança já desconte o peso do prato."""

peso = float(input('digite o peso total do prato (em Kg) de comida: '))

pagar = peso * 12

print('voce deve pagar: R$', pagar)

"""7. Entrar com o dia e o mês de uma data e informar quantos dias se passaram desde o início do ano. Esqueça a questão dos anos bissextos e considere sempre que um mês possui 30 dias."""

dias = int(input('Digite o dia do mês (1-30): '))
mes = int(input('Digite o número do mês (1-12): '))
dias_passados = dias + ((mes - 1) * 30)
print(f'Já se passaram {dias_passados} dias')

"""8. Faça um script em Python para ler três notas de um aluno em uma disciplina e imprimir a sua média ponderada (as notas tem pesos respectivos de 1, 2 e 3)."""

nota1 = float(input('Digite a nota 1: '))
nota2 = float(input('Digite a nota 2: '))
nota3 = float(input('Digite a nota 3: '))

mp = ((nota1 * 1) + (nota2 * 2) + (nota3 * 3)) / (1 + 2 + 3)

print('A média ponderada do aluno é:', mp)

"""9. Uma fábrica de camisetas produz os tamanhos pequeno, médio e grande, cada uma sendo vendida respectivamente por 10, 12 e 15 reais. Construa um script em Python em que o usuário forneça a quantidade de camisetas pequenas, médias e grandes referentes a uma venda, e a máquina informe quanto será o valor arrecadado."""

qtd_camiseta_pequena = int(input('Digite a quantidade de camisetas pequenas compradas: '))
qtd_camiseta_media = int(input('Digite a quantidade de camisetas médias compradas: '))
qtd_camiseta_grande = int(input('Digite a quantidade de camisetas grandes compradas: '))

total_pequena = qtd_camiseta_pequena * 10
total_media = qtd_camiseta_media * 12
total_grande = qtd_camiseta_grande * 15

total = total_pequena + total_media + total_grande

print('O valor total arrecadado é R$', total)

"""10. Uma fábrica controla o tempo de trabalho sem acidentes pela quantidade de dias. Faça um script em Python para converter este tempo em anos, meses e dias. Assuma que cada mês possui sempre 30 dias."""

dias_sem_acidentes = int(input('Digite a quantidade de dias sem acidentes: '))

anos = dias_sem_acidentes // 360
dias = dias_sem_acidentes % 30

if (anos > 0):
  meses = (dias_sem_acidentes // 30) - (anos * 12)
else:
  meses = dias_sem_acidentes // 30

print(f'Sem acidentes há {anos} anos {meses} mes(es) e {dias} dia(s).')

"""11. Faça um script em Python para ler o salário de um funcionário e aumentá-Io em 15%. Após o aumento, desconte 8% de impostos. Imprima o salário inicial, o salário com o aumento e o salário final."""

salario = float(input('Digite o valor do seu salário R$: '))

aumento_15 = salario + (salario * 0.15)
desconto_imposto = aumento_15 - (aumento_15 * 0.08)

print(f'o salário inicial foi R${salario}, com aumento de 15%: R${aumento_15} e subtraído os descontos de 8% referente ao imposto: R${desconto_imposto}')

"""12. Ler um número inteiro (assuma até três dígitos) e imprimir a saída da seguinte forma:
CENTENA = x
DEZENA = x
UNIDADE = x
"""

num = input('digite um número inteiro com 3 digitos: ')
print(f'Centena:{num[0]}, Dezena:{num[1]} e Unidade:{num[2]}')

"""13. Calcule a área de uma pizza que possui um raio R (pi=3.14)."""

raio = float(input('Digite o valor do raio da pizza: '))
area = 3.14 * (raio ** 2)
print('A área da pizza é:', area)

"""14. A lanchonete Gostosura vende apenas um tipo de sanduíche, cujo recheio inclui duas fatias de queijo, uma fatia de presunto e uma rodela de hambúrguer. Sabendo que cada fatia de queijo ou presunto pesa 50 gramas, e que a rodela de hambúrguer pesa 100 gramas, faça um script em Python em que o dono forneça a quantidade de sanduíches a fazer, e a máquina informe as quantidades (em quilos) de queijo, presunto e carne necessários para compra."""

sanduiches = int(input('Digite a quantidade de sanduiches a serem feitos: '))

queijo = (sanduiches * 2) * 0.05
presunto = sanduiches * 0.05
hamburguer = sanduiches * 0.1

print(f'Serão necessários {queijo}Kg de queijo, {presunto}Kg de presunto e {hamburguer}Kg de hamburguer')

"""15. Alguns países medem temperaturas em graus Celsius, e outros em graus Fahrenheit. Faça um script em Python para ler uma temperatura Celsius e imprimi-Ia em Fahrenheit (pesquise como fazer este tipo de conversão)."""

temperatura = int(input('digite a temperatura em fahrenheit: '))
celsius = (temperatura - 32) * (5/9)
print('a temperatura em celsius e:', celsius)

"""16. A empresa Hipotheticus paga 10,00 por hora normal trabalhada, e 15,00 por hora extra. Faça um script em Python para calcular e imprimir o salário bruto e o salário líquido de um determinado funcionário. Considere que o salário líquido é igual ao salário bruto descontando-se 10% de impostos."""

horas_trabalhadas = int(input('Digite o valor de horas trabalhadas: '))
horas_extras = int(input('Digite o valor de horas extras trabalhadas: '))

salario_bruto = (horas_trabalhadas * 10) + (horas_extras * 15)

salario_liquido = salario_bruto - (salario_bruto * 0.1)

print(f'O salário bruto é R${salario_bruto} e o salário líquido R${salario_liquido}')

"""17. A granja Frangotech possui um controle automatizado de cada frango da sua produção. No pé direito do frango há um anel com um chip de identificação; no pé esquerdo são dois anéis para indicar o tipo de alimento que ele deve consumir. Sabendo que o anel com chip custa 4.00 e o anel de alimento custa 3.50, faça um script em Python para calcular o gasto total da granja para marcar todos os seus frangos.

"""

galinhas = int(input('Digite a quantidade de galinhas da granja: '))

anel_chip_pe_direito = galinhas * 4
aneis_alimentacao_pe_esquerdo = galinhas * (3.5 * 2)

gasto_total = anel_chip_pe_direito + aneis_alimentacao_pe_esquerdo

print('O gasto total da granja Frangotech é:', gasto_total)

"""18. Uma confecção produz X blusas de lã e para isto gasta uma certa quantidade de novelos. Faça um script em Python para calcular quantos novelos de lã ela gasta por blusa."""

blusas = int(input('Digite a produção de blusas: '))
novelos = float(input('Digite a quantidade de novelos utilizados na produção: '))

novelos_por_blusa = novelos / blusas

print(f'São gastos {novelos_por_blusa} novelos por blusa')

"""19. A fábrica de refrigerantes Meia-Cola vende seu produto em três formatos: lata de 350 ml, garrafa de 600 ml e garrafa de 2 litros. Se um comerciante compra uma determinada quantidade de cada formato, faça um script em Python para calcular quantos litros de refrigerante ele comprou."""

lata_350 = int(input('Digite a quantidade de latas de 350ml compradas: '))
garrafa_600 = int(input('Digite a quantidade de garrafas de 600ml compradas: '))
garrafa_2 = int(input('Digite a quantidade de garrafas de 2 litros compradas: '))

litros_lata = lata_350 * 0.350
litros_garrafa600 = garrafa_600 * 0.600
litros_garrafa2 = garrafa_2 * 2

total_litros = litros_lata + litros_garrafa600 + litros_garrafa2

print('A qantidade de litros de refrigerante comprado foi:', total_litros)

"""20. Um tonel de refresco é feito com 8 partes de água mineral e 2 partes de suco de maracujá. Faça um script em Python para calcular quantos litros de água e de suco são necessários para se fazer X litros de refresco (informados pelo usuário)."""

litros_refresco = float(input('Informe a quantidade de litros de refresco a serem produzidos: '))

qtd_agua = litros_refresco * 0.8
qtd_suco = litros_refresco * 0.2

print(f'A quantidade de litros de água necessário é {qtd_agua} e a quantidade de litros de suco necessário é {qtd_suco}')

"""21. Calcule o volume de uma caixa d'água cilíndrica."""

altura = float(input('Digite a altura da caixa dagua: '))
raio = float(input('Digite o valor do raio da base da caixa dagua: '))
pi = 3.14

volume_cilindro = pi * (raio**2) * altura

print('O volume da caixa dagua é', volume_cilindro)

"""22. Faça um script em Python que receba três números, calcule e mostre a multiplicação desses números."""

num1 = float(input('Digite o primeiro numero: '))
num2 = float(input('Digite o segundo numero: '))
num3 = float(input('Digite o terceiro numero: '))

total = num1 * num2 * num3

print('A multiplicação dos números é:', total)

"""23. Faça um script em Python que receba dois números, calcule e mostre a divisão do primeiro número pelo segundo. Sabe-se que o segundo número não pode ser zero, portanto não é necessário se preocupar com validações."""

num1 = float(input('Digite o primeiro numero: '))
num2 = float(input('Digite o segundo numero: '))

divisao = num1 / num2

print('A divisão do primeiro número pelo segundo:', divisao)

"""24. Faça um script em Python que receba duas notas, calcule e mostre a média ponderada dessas notas, considerando peso 2 para a primeira nota e peso 3 para a segunda nota."""

nota1 = float(input('Digite a nota 1: '))
nota2 = float(input('Digite a nota 2: '))


mp = ((nota1 * 2) + (nota2 * 3)) / (2 + 3)

print('A média ponderada do aluno é:', mp)

"""25. Faça um script em Python que receba o preço de um produto, calcule e mostre o novo preço, sabendo-se que este sofreu um desconto de 10%."""

preco = float(input('Digite o preço do produto: '))

desconto = preco - (preco * 0.1)

print('O novo preço do produto é:', desconto)

"""26. Um funcionário recebe um salário fixo mais 4% de comissão sobre as vendas. Faça um script em Python que receba o salário fixo de um funcionário e o valor de suas vendas, calcule e mostre a comissão e o salário final do funcionário.

"""

salario = float(input('Digite o valor do seu salário fixo R$: '))
valor_vendas = float(input('Digite o valor total de suas vendas R$: '))

comissao = valor_vendas * 0.04
total = salario + comissao

print(f'O salário final do funcionário é R$ {total}, adicionado comissão R$ {comissao}')

"""27. Faça um script em Python que receba o peso de uma pessoa, calcule e mostre:<br> 
a) o novo peso se a pessoa engordar 15% sobre o peso digitado;<br>
b) o novo peso se a pessoa emagrecer 20% sobre o peso digitado.
"""

peso = float(input('Digite se peso atual em kg: '))
engordar = peso + (peso * 0.15)
emagrecer = peso - (peso * 0.2)

print(f'o novo peso se a pessoa engordar {engordar}Kg / o novo peso se a pessoa emagrecer {emagrecer}Kg')

"""28. Faça um script em Python que receba o peso de uma pessoa em quilos, calcule e mostre esse peso em gramas."""

peso = float(input('Digite se peso atual em kg: '))

gramas = peso * 1000

print('O peso em gramas é:', gramas)

"""29. Faça um script em Python que calcule e mostre a área de um trapézio. Sabe-se que: A = (base maior + base menor)* altura)/2"""

base_maior = float(input('Digite o valor da base maior: '))
base_menor = float(input('Digite o valor da base menor: '))
altura = float(input('Digite o valor da altura: '))

area_trapezio = ((base_maior + base_menor) * altura) / 2

print('A área do trapézio é', area_trapezio)

"""30. Faça um script em Python que calcule e mostre a área de um quadrado. Sabe-se que: A = lado * lado;"""

quadrado = float(input('Digite o valor de um dos lados do quadrado: '))

area_quad = quadrado * quadrado

print('A area do quadrado é:', area_quad)

"""31. Faça um script em Python que calcule e mostre a área de um losango. Sabe-se que: A = (diagonal_maior * diagonal_menor)/2;"""

diagonal_maior = float(input('Digite o valor da diagonal maior: '))
diagonal_menor = float(input('Digite o valor da diagonal menor: '))

area = (diagonal_maior * diagonal_menor) / 2

print('A área do losango é:', area)

"""32. Faça um script em Python que receba o valor do salário-mínimo e o valor do salário de um funcionário, calcule e mostre a quantidade de salários mínimos que ganha esse funcionário."""

salario_min = float(input('Digite o valor do salário minimo: '))
salario = float(input('Digite o valor do salário do funcionário: '))

qtd_salario = salario / salario_min

print('A quantidade de salários minimos que o funcionário recebe é:', qtd_salario)

"""33. Faça um script em Python que calcule e mostre a tabuada de um número digitado pelo usuário."""

numero = int(input('Digite um número para que a tabuada seja impressa: '))

i = 1

while i <= 10:
  print(numero * i)
  i += 1

"""34. Faça um script em Python que receba o ano de nascimento de uma pessoa e o ano atual, calcule e mostre:<br>
a) a idade dessa pessoa em anos;<br>
b) a idade dessa pessoa em meses;<br>
c) a idade dessa pessoa em dias;<br>
d) a idade dessa pessoa em semanas.
"""

data_nasc = int(input('Digite o ano de nascimento: '))
data_atual = int(input('Digite o ano atual: '))

em_anos = data_atual - data_nasc
em_meses = em_anos * 12
em_dias = em_anos * 365
em_semanas = em_anos * 12 * 4

print('Sua idade em anos é:', em_anos)
print('Sua idade em meses é', em_meses)
print('Sua idade em dias é:', em_dias)
print('sua idade em semanas é:', em_semanas)