# -*- coding: utf-8 -*-
"""Tarefa 6 Strings

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18yh8bvwlmv5UfX1Movh9HlPBaDx1b6Mo

1) Faça um script que leia seu nome completo e exiba: todo em maiúsculo, todo em minúsculo, a quantidade de letras que ele possui (sem os espaços em branco) e somente seu primeiro nome e sua quantidade de letras;
"""

nome = input('Digite o seu nome completo: ')
# minúscula
nome_lower = nome.lower()
# maiúscula
nome_upper = nome.upper()
# contar sem espaços
nome_count = len(nome.replace(" ", ""))
# primeiro nome
nome_primeiro = nome.split()[0]
# qtd. letras primeiro nome
nome_count_primeiro = len(nome_primeiro)

print('Nome em caixa baixa:', nome_lower)
print('Nome em caixa alta:', nome_upper)
print('Qtd de letras sem espaços', nome_count)
print('Somente primeiro nome e qtd. letras:', nome_primeiro, nome_count_primeiro)

"""2) Faça um script que leia um número de 4 dígitos e informe a quantidade de milhar, centena, dezena e unidade;"""

num = input("Digite um número de 4 dígitos: ")

try:
  num = int(num)

  # Separa cada dígito do número
  milhar = num // 1000
  centena = (num % 1000) // 100
  dezena = (num % 100) // 10
  unidade = num % 10

  # Exibe a quantidade de cada dígito
  print("Milhar:", milhar)
  print("Centena:", centena)
  print("Dezena:", dezena)
  print("Unidade:", unidade)
except ValueError:
  print('Entre com um número válido!')

"""3) Faça um script que leia uma frase qualquer e verifique se ela começa com Ciências;"""

frase = input("Digite uma frase: ").lower()

# Verifica se a frase começa com "Ciências"
if frase.startswith("ciências"):
    print("A frase começa com 'Ciências'")
else:
    print("A frase não começa com 'Ciências'")

#A função startswith() é utilizada para verificar se a frase começa com a string "Ciências".

"""4) Faça um script que leia um nome de curso e verifique se tem Dados no nome do curso;"""

curso = input("Digite o nome do curso: ").lower()

# Verifica se o nome do curso contém "Dados"
if "dados" in curso:
    print("O nome do curso contém 'Dados'")
else:
    print("O nome do curso não contém 'Dados'")

"""5) Faça um script que leia um nome (desconsidere acentos) e verifique quantas vezes aparece a letra A, qual a primeira posição que a letra A aparece e qual a última posição também;"""

!pip install unidecode  # Instala a biblioteca unidecode
from unidecode import unidecode

nome = unidecode(input("Digite um nome: ").lower())

# Conta a quantidade de vezes que a letra "a" aparece no nome
qtd_a = nome.count("a")

# Encontra a posição da letra "a"
primeira_a = nome.find("a")
ultima_a = nome.rfind("a")

# Exibe os resultados
print("Quantidade de vezes que a letra 'a' aparece:", qtd_a)
if primeira_a >= 0:
    print("Primeira posição da letra 'a':", primeira_a)
else:
    print("A letra 'a' não foi encontrada no nome.")
if ultima_a >= 0:
    print("Última posição da letra 'a':", ultima_a)
else:
    print("A letra 'a' não foi encontrada no nome.")

"""6) Faça um script que leia o nome completo de uma pessoa e exiba o primeiro e o último nome somente."""

nome_completo = input("Digite o nome completo: ")

# Separa o nome completo em uma lista de palavras
palavras = nome_completo.split()
primeiro_nome = palavras[0]
ultimo_nome = palavras[-1]

print("Primeiro nome:", primeiro_nome)
print("Último nome:", ultimo_nome)