# -*- coding: utf-8 -*-
"""TRABALHO MATEMÁTICA / ALGORITMOS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s9Bzg1UMl8vGjBGrUSqHaZh1L4K1YePM

Numa equipe de programadores, 28 programam em JAVA, 12 programam em
COBOL e 8 programam em JAVA e COBOL. Quantos programadores há nesta
equipe? Quantos só programam em JAVA?
"""

import matplotlib.pyplot as plt
from matplotlib_venn import venn2

# Dados fornecidos no exercício
programadores_java = 28
programadores_cobol = 12
programadores_java_cobol = 8

# Calculando a quantidade de programadores que só programam em JAVA
programadores_apenas_java = programadores_java - programadores_java_cobol

# Calculando a quantidade de programadores que só programam em COBOL
programadores_apenas_cobol = programadores_cobol - programadores_java_cobol

# Calculando a quantidade total de programadores
total_programadores = programadores_apenas_java + programadores_apenas_cobol + programadores_java_cobol

# Criando o diagrama de Venn
venn = venn2(subsets=(programadores_apenas_java, programadores_apenas_cobol, programadores_java_cobol),
             set_labels=('JAVA', 'COBOL'))

# Adicionando o título ao diagrama
plt.title('Diagrama de Venn - Equipe de Programadores')

# Exibindo o diagrama
plt.show()

print ('_______________________________')
print('Respostas:')
print('Existem', total_programadores, 'programadores na equipe.')
print('Existem', programadores_apenas_java,'programadores que utilizam somente Java.')

import matplotlib.pyplot as plt
from matplotlib_venn import venn2
#qtd limite de grupos conforme biblioteca

# Dados fornecidos no exercício
nomes_grupos = []
qtd_grupos = []
num_grupos = 2

total = int(input(f'Digite a quantidade total de elementos presentes nos {num_grupos} conjuntos: '))

for grupo in range(1, 3, 1):
  nome = input(f'Digite um nome para o grupo {grupo}:').upper()
  qtd = int(input(f'Digite a quantidade de elementos do grupo {grupo}:'))
  nomes_grupos.append(nome.strip(" "))
  qtd_grupos.append(qtd)

if total < (qtd_grupos[0] + qtd_grupos[1]):
  print('O número TOTAL de elementos é MENOR do que o número de elementos em cada grupo!!!')
else:
  intersec = int(total - (qtd_grupos[0] + qtd_grupos[1]))

  # Criando o diagrama de Venn
  venn = venn2(subsets=(qtd_grupos[0], qtd_grupos[1], intersec),
              set_labels=(nomes_grupos[0], nomes_grupos[1]))

  # Adicionando o título ao diagrama
  plt.title('Diagrama de Venn - Conjuntos')

  # Exibindo o diagrama
  plt.show()

  print ('_______________________________')
  print('Respostas:')
  print('Existem', total, 'elementos nos conjuntos.')
  print('Existem', intersec,'elementos que participam de ambos conjuntos')